### ISSUE TITLE
Instead of just being able to hide the backlog, be able to select columns to view

### ISSUE THREAD

**Issue by captainwasabi** [leif81/bzkanban#67] opened 2017-04-06 16:15 UTC
We don't use Unconfirmed in our workflow at all. In most cases I'd personally just want to see New, Assigned, and Reopened. Other uses may vary (while doing regression testing maybe just Resolved and Verified.

Implemented maybe as "Set Columns" rather than Hide/Show Backlog, then bring up a dialog where columns that are desired are selected via checkbox.

**Comment by leif81** [comment] 2017-04-06 16:25
Hi @captainwasabi , thankyou for the report.

One thing you could do about the UNCONFIRMED column is turn it off in your Bugzilla server. There's a flag under _Administration -> Products_ called _Enable the UNCONFIRMED status in this product_.

**Comment by captainwasabi** [comment] 2017-04-06 16:28
Ah, ok, my comment was based on trying out the demo.  I have not installed it on my server yet, but I'll be installing it just as soon as I have half a chance, so UNCONFIRMED would have actually not shown up at all because I do have it turned off :)

BTW, I have been looking for something like this that works for a REALLY long time.  Thank you!

**Comment by leif81** [comment] 2017-04-06 17:00
Cool happy to hear that!

Btw, this would obviously be a hack, but if you are desperate to try hiding other columns, for now you could modify the DOM manually in your browser dev tools console like this:

`document.querySelector("#VERIFIED").style.display = "none";`

**Comment by captainwasabi** [comment] 2017-04-06 18:32
Just for anyone interested you can create a bookmarklet with the following:

javascript:void(document.querySelector("#VERIFIED").style.display = "none"); void(document.querySelector("#CLOSED").style.display = "none");

And to show the columns again:

javascript:void(document.querySelector("#VERIFIED").style.display = null); void(document.querySelector("#CLOSED").style.display = null);

**Comment by captainwasabi** [comment] 2017-04-09 00:31
To toggle columns try this as a bookmarklet:

javascript:(
  function(){

    function create(htmlStr) {
      var frag = document.createDocumentFragment(),
          temp = document.createElement('div');
      temp.innerHTML = htmlStr;
      while (temp.firstChild) {
          frag.appendChild(temp.firstChild);
      }
      return frag;
    }

    _my_script=document.createElement('SCRIPT');
     _my_script.type='text/javascript';
     _my_script.src='https://rawgit.com/captainwasabi/d41a1e3183247e5a762ac2c96829887f/raw/1b709fe5b65cb21d1b660e75b0c5d9c87e9a9b1e/colsel.js';
     document.getElementsByTagName('head')[0].appendChild(_my_script);

    var statusHtmlStr = "";
    httpGet("/rest.cgi/field/bug/status/values", function(response) {
      var statuses = response.values;
      statuses.forEach(function(status) {
        console.log("Col Name: " + status);
        statusHtmlStr = statusHtmlStr + '<a onclick=javascript:tog("' + status + '"); href="javascript:void(0);"> '+ status +' </a>'
      });
      statusHtmlStr = statusHtmlStr + '<br>  ';
      var statusColStr = create(statusHtmlStr);
      document.body.insertBefore(statusColStr, document.body.childNodes[0]);
    });
  }
)();

**Comment by leif81** [comment] 2017-04-09 01:09
Thankyou for sharing this. I had not thought of injecting javascript into a bookmarklet. That seems like a good way to make small customizations without having to fork the board. 

Btw, I think the idea of hiding some columns is a reasonable ask. Howver since you've got a good workaround and it seems like you're requirement fits a pretty specific workflow for your purposes, I hope you don't mind I'll close this issue and leave it at that.

**Closed as completed by leif81** 2017-04-09 01:09 UTC
Labels: enhancement, wontfix
